version: "3.8"

services:
  forecasting:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: forecasting_container
    volumes:
      - ../:/app
    command: tail -f /dev/null
